### ISSUE TITLE
Unable to load the coin types list

### ISSUE THREAD

**Issue by ethan520** [hexters/CoinPayment#10]
<img width="1124" alt="screen shot 2018-08-06 at 11 38 51 am" src="https://user-images.githubusercontent.com/16395613/43695802-572b307a-996d-11e8-8b55-106d06468226.png">

I've integrated the coinpayment module as stated in the readme, but i couldn't see the list of coin methods when i try to create new transaction, did i missed out something?

**Comment by hexters** [comment]
First activate the coin needed at https://www.coinpayments.net

**Comment by hexters** [comment]
<img width="1140" alt="screen shot 2018-08-08 at 11 29 58 am" src="https://user-images.githubusercontent.com/7827420/43816354-726a284a-9afe-11e8-8658-54513fd97119.png">

**Comment by ethan520** [comment]
Thanks for the prompt reply!! It works now! =D
