### ISSUE TITLE
CoinPayment Facade not found

### ISSUE THREAD

**Issue by andma1** [hexters/CoinPayment#11]
![image](https://user-images.githubusercontent.com/41778180/45839585-d2085080-bd25-11e8-9c3a-c366e5fd2b99.png)

How can i import Coinpayment facade?

**Comment by HDVinnie** [comment]
At the top of your controller add `use CoinPayment;`

**Comment by andranik-m** [comment]
What is it's namespace?

**Comment by hexters** [comment]
you can use 
``` 
. . .
\ CoinPayment::url_payload($trx);
. . . 
```
