### ISSUE TITLE
it doest help, maybe i installed th package  incorrect, because i dont have this facade in your folder in vendor

### ISSUE THREAD

**Issue by andranik-m** [hexters/CoinPayment#12]
``` 
. . .
\CoinPayment::url_payload($trx);
. . . 
```

_Originally posted by @hexters in https://github.com/hexters/CoinPayment/issues/11#issuecomment-423856351_

I
![image](https://user-images.githubusercontent.com/43211481/45978405-5841d100-c05d-11e8-9f2e-04fc3e311aff.png)

I looked for this class here  in vendor
![image](https://user-images.githubusercontent.com/43211481/45978447-7b6c8080-c05d-11e8-935d-c2e6540226d3.png)

**Comment by hexters** [comment]
Try ``` composer dump-autoload```

**Comment by andranik-m** [comment]
did not help

**Comment by andranik-m** [comment]
another solutions?

**Comment by hexters** [comment]
```
/* use CoinPayment class on outside controller class */
use CoinPayment;

. . . 

/* in your controller  */
$link = CoinPayment::url_payload($trx);

```
