### ISSUE TITLE
Payment Methods are not Loading

### ISSUE THREAD

**Issue by nasirkhannstu** [hexters/CoinPayment#18]
![payment](https://user-images.githubusercontent.com/19144572/51473040-6acadd80-1da5-11e9-999b-2b5e19a168f2.png)

**Comment by nasirkhannstu** [comment]
My Console
![console](https://user-images.githubusercontent.com/19144572/51473166-c85f2a00-1da5-11e9-8728-894516b7c62f.png)

**Comment by hexters** [comment]
Open network tab, click response error in your list request.  click preview and see what the error ?

**Comment by nasirkhannstu** [comment]
![network](https://user-images.githubusercontent.com/19144572/51513374-c3958700-1e34-11e9-856f-dbee98a16621.png)
This is my network tab. I Did exactly how documentation tells to do.

**Comment by JJRuizSeisCocos** [comment]
Same problem here

**Comment by nasirkhannstu** [comment]
@JJRuizSeisCocos is everything working with this fixes??

**Comment by JJRuizSeisCocos** [comment]
Yes, fixed. Everything working fine for me.

**Comment by nasirkhannstu** [comment]
@hexters it this the desired way to do this? Please answer.

**Comment by hexters** [comment]
I think this in problem from https://www.coinpayments.net please checking again for your account setting

**Comment by nasirkhannstu** [comment]
Can you please give me some hints which settings should i double check??

**Comment by divino11** [comment]
@hexters, Hi, how to solve this problem, do you have idea?
I do not want to go to the vendor)

**Comment by kasus** [comment]
@hexters this problem is solved already in the master branch, but it doesn't have version tag. That's why composer install 1.1.3 version, which is not the latest

**Comment by shoutershub** [comment]
i don't like the ideal of editing my vendor file to clear this error, any other alternative, plus i tried reinstalling the package again same issue, for now i would settle for editing my vendor file, hopefully till this is resolved.
