### ISSUE TITLE
Division by Error

### ISSUE THREAD

**Issue by shoutershub** [hexters/CoinPayment#19]
Hello, sorry i know this is a duplicate thread, but i have searched on the issue on this repo and no option rendered worked for me please.

Please How do i get this to work for me, i have  tried this two option to no avail  [https://github.com/hexters/CoinPayment/issues/10,  https://github.com/hexters/CoinPayment/issues/18 ], worse yet i have even edited the coin payment controller code in the vendor package still no success. 

https://github.com/hexters/CoinPayment/issues/10

**Comment by hexters** [comment]
Tanks to report bug in this package.

try to Update version v1.1.5
