### ISSUE TITLE
what problem here? 

### ISSUE THREAD

**Issue by nurkarim** [hexters/CoinPayment#20]
![image](https://user-images.githubusercontent.com/24413383/56085991-1ba9bb80-5e6f-11e9-83a0-a71acefb77fb.png)
Hello, I don't know why this problem shows me.

**Comment by hexters** [comment]
showing trxinfo network please

**Comment by nurkarim** [comment]
problem solved

**Comment by nurkarim** [comment]
it was an api permission error.

**Comment by nurkarim** [comment]
Thank you.
