### ISSUE TITLE
Carbon PHP

### ISSUE THREAD

**Issue by atmediauk** [hexters/CoinPayment#22]
Any chance of updating the package dependencies? Particularly nesbot/carbon to ^2.0

**Comment by nagsamayam** [comment]
Hi @hexters , thanks for providing this package. Is there is any possibility/plan to update nesbot/carbon package to V2?

**Comment by angeldelacruzsdo** [comment]
Clone and paste this  "nesbot/carbon": "^2.21.3" on your repository CoinPayment

**Comment by hexters** [comment]
cek v2.0.0
