### ISSUE TITLE
I got the link in local and the payment form isn't pop up.

### ISSUE THREAD

**Issue by yenkhoon** [hexters/CoinPayment#27]
Hi there, the payment form isn't redirect/pop up to. Instead I'm getting a link as below.

http://secret.test/coinpayment/make/eyJpdiI6InN2dGRENVp0RzFmdEYrd1JVWGhmNWc9PSIsInZhbHVlIjoiNjlKN0xub3RMRnd3T3Z6MWlQdlhEOU03a1NZWFhLaTYzNXE5bjlZZHdLZEJlUVluV000OGdhUVJZemNSZmZKQVVuRmRBXC9URkM5N1Z6cGhnYWhDWExMbG5XeXp3bFJBNHdSZlY2cnZvcFdVeXpTZ3NKZFVMRTJcLzZNYXg0MkF6dXRnSVZLS2dpY0JHRTNvbnJEUGRwVTU5TlJnT29kOVBiNDhyUGJhVU5NUnZhalRRNmlVOXQ4UGc1bGhqZ3RRYlh6dU1vblJTdTFxeW1DRjdzTHR2cUJncitmTDFkSVh3U1Z1UlBndnc3VTExNDVvd0lCb0VxVFo3NFIrODByVk14azJacVM4d3NIdG5zOCs3U1lHalwvb2VxS0R2RWtWYnkwY2owY0FzMVczcE1tMDdtSnpTZEgrS0tRcUZIZUdCS2N2YzZKdWw1dFhuYk9LMlozbEZua0VhQUtaOVk2RWptUytpRzJKRWpHTExhWFpKTVhJeVc5Z0VhWUZ5SlVsekF4SWNCRnhvT3dzM1hNTkFjYzFyZTlQbGtPcGtzalEyUWtFSlNBbXZ3Zk9BTHQ3dGZLWXhJXC9jTEFPRW8rNmRWdm95WTdDTGRRbTFKd2pFY3I2XC9ZdkNwV04yeUFMWEdnRVlTdFBsaWVnM1JOVFViUU9OUzQ5ZlBCUjNSREZHWkVCaXV1cFp3SjVLWTIxRW43cFFUQlVJM29Wb3d3YXU4SUVQXC9LSTVvM2o1SGJ2dXV1c3pkemoxSmNDTXp1WnZjWmpUOXl2ZnE0OTNoaFJEUGl3UTN5NmNNTGtHVGFVQmZZUHB2NDRIcDhycGZKblVjVE9Rdm5qeDNRMHJUUit6Tkxib3RIaytWRXU1bWJsb29aVjRGdmFDdWpBYlRxdXdUclwvNVg3akVhQ1dKMG11WUFlcW5nd3pnb2ZwMWJUUjVqVVdXeDBEQ3Z6ZkVhTVRTdUMzR0Zta1V2WVY1ZlR5UDlNaTdXQjM3U3BvdGQ0Q0Z3dmpSN1U4dE45dFc2aUxyZDJyaWUyQW9aN0xZNW1vVm9SOGhCNVM2T1RPVUxST01EcEN6OEpRNkc2T3ZEWkhyMkVQM0s2TVwvdk9TUzJsR2V4TnliNWtrQWY2a2lBMlNsQmFKb1V2V2xUZz09IiwibWFjIjoiNTg5MDAxZWUxMWJhZjNjMzY4MmFjODAzNTgzYWZjMTM1ZGFlYjMwZjlmNWUwYTQyYTNjZjQ5MDU2MmYwODZjNiJ9

Environment: local
Php version: 7.3
laravel version: 5.8

**Comment by hexters** [comment]
the transaction process does not work using popups.  You must redirect with the current tab.  then adjust the callback link
