### ISSUE TITLE
Cannot use object of type Illuminate\Http\JsonResponse as array

### ISSUE THREAD

**Issue by thevis009** [hexters/CoinPayment#29]
I tried with laravel 5.6 issue in transaction create: Something look like wrong.

Now I try it with laravel 5.8, I receive :

Cannot use object of type Illuminate\Http\JsonResponse as array

How can I solve this issue please?

**Comment by kitspoitwaecy** [comment]
Did you find the solution already? I have also the same error.

**Comment by hexters** [comment]
I think `Illuminate\Http\JsonResponse` ready on version 5.8 [https://laravel.com/api/5.8/Illuminate/Http/JsonResponse.html](https://laravel.com/api/5.8/Illuminate/Http/JsonResponse.html)

**Comment by hexters** [comment]
For me everything is well see this video [Example Video](https://www.loom.com/share/a58f9cee98aa4fe6811b9d2c30ba8116)

**Comment by kitspoitwaecy** [comment]
What is your solution?

**Comment by kitspoitwaecy** [comment]
I'm using laravel 6.x, and it always show Illuminate\Http\JsonResponse
What i'm going to use? 5.8? version?

**Comment by kitspoitwaecy** [comment]
[https://fastbit.ielev8net.com/assets/images/error.png](url)
that's the error.

**Comment by hexters** [comment]
Your coin has active?

**Comment by hexters** [comment]
I think your plublem in coinpayment configuration

**Comment by paulwaldmann** [comment]
For anyone experiencing this issue in the future, make sure you whitelist the IP from where you're accessing the API from. After adding the IP, it worked like a charm.

https://www.coinpayments.net/index.php?cmd=acct_api_keys
