### ISSUE TITLE
stock on loading after click the payment button

### ISSUE THREAD

**Issue by kitspoitwaecy** [hexters/CoinPayment#30]
[https://fastbit.ielev8net.com/assets/images/error2.png](https://fastbit.ielev8net.com/assets/images/error2.png)

Please see this link

**Comment by hexters** [comment]
Please see response from server, click network tab and review for the response

**Comment by kitspoitwaecy** [comment]
[https://fastbit.ielev8net.com/assets/images/error3.png](https://fastbit.ielev8net.com/assets/images/error3.png)
where can I find sorry

**Comment by kitspoitwaecy** [comment]
[https://fastbit.ielev8net.com/assets/images/error4.png](https://fastbit.ielev8net.com/assets/images/error4.png)

apache, what is the problem with that, you think?

**Comment by kitspoitwaecy** [comment]
[https://fastbit.ielev8net.com/assets/images/error4.png](https://fastbit.ielev8net.com/assets/images/error4.png)

Here is the response from server.

**Comment by hexters** [comment]
```
$ php artisan vendor:publish --tag=coinpayment
```
And check file `app/Jobs/CoinpaymentListener.php`

**Comment by buildbro** [comment]
I am facing same issue. I ran vendor:publish and go the following:
```
ea (master *+) spiritgram $ php artisan vendor:publish --tag=coinpayment
Copied Directory [/vendor/hexters/coinpayment/src/Resources/assets/images] To [/public]
Publishing complete.
ea (master *+) spiritg
```
I also have app/Jobs/CoinpaymentListener.php in my project.
