### ISSUE TITLE
Can't find CoinpaymentListener.php

### ISSUE THREAD

**Issue by kitspoitwaecy** [hexters/CoinPayment#31]
[https://fastbit.ielev8net.com/assets/images/error6.png](https://fastbit.ielev8net.com/assets/images/error6.png)
[https://fastbit.ielev8net.com/assets/images/error7.png](https://fastbit.ielev8net.com/assets/images/error7.png)

It's already there but I have the same error?

**Comment by hexters** [comment]
`composer dumpautoload`

**Comment by kitspoitwaecy** [comment]
ok, i'll try that.

**Comment by kitspoitwaecy** [comment]
[https://fastbit.ielev8net.com/assets/images/done.png](https://fastbit.ielev8net.com/assets/images/done.png)

already running thank you very much. your the best.

**Comment by hexters** [comment]
your welcome
