### ISSUE TITLE
Can't add additional params to 'create transaction' api call

### ISSUE THREAD

**Issue by lokilok1993** [hexters/CoinPayment#4]
in CoinPaymentController 
function make_transaction
does not accept any params for specify not required fields like buyer_email.

**Comment by hexters** [comment]
You can use 
```
. . . 
$trx['payload'] = [
        // your cusotm array here
        'foo' => [
            'foo' => 'bar'
        ]
    ];
. . . 

```
payload parameters will be stored in the database, will be in the call again. to integrate with your application
