### ISSUE TITLE
message: "The payload is invalid."

### ISSUE THREAD

**Issue by vdjkelly** [hexters/CoinPayment#47]
```
  $trx['payload'] = [
                // your cusotm array here
                'foo' => [
                    'foo' => 'bar'
                ]
            ];
```

`500 Internal Server Error message: "The payload is invalid."`

**Comment by hexters** [comment]
What your laravel version?

**Comment by vdjkelly** [comment]
> What your laravel version?
**^6.0.0**

get processed payment response, some example of how to get it, first time I work with with cryptocurrencies, I don't speak English. Thank's

**Comment by hexters** [comment]
Please check again your payload data, your data must be an array
