### ISSUE TITLE
Request help to edit formTransaction.vue file

### ISSUE THREAD

**Issue by tftwebteam** [hexters/CoinPayment#49]
Kindly help me to edit the formTransaction.vue file, unable to remove velas.old coin from payment page and Tether USD icon is not showing. Please help me to solve these issues.

Thank you

**Comment by hexters** [comment]
Disable your velas.old coin in coinpayments configuration.

**Comment by tftwebteam** [comment]
Thank you so much for your valuable reply and also can you please help me how to edit formTransaction.vue file? And Tether USD icon is not showing.
Please your help means a lot.
