### ISSUE TITLE
Ajax 500 Error

### ISSUE THREAD

**Issue by KaranSadana** [hexters/CoinPayment#5]
I follow your turorial in readme file. i did all and by clicking pay now ,am redirecting to new page as written in read me. now the problem is when on new page which is vue.js page i click on pay now...its an error "ajax/trxinfo 500 (Internal Server Error)" which i saw in console window. can you please guide me , how to solve this,

**Comment by hexters** [comment]
error on line to how?

**Comment by thevis009** [comment]
I have not be able yet to solve this problem once i follow and install this process payment coinpayment.
Each time i Click pay now i receive  the screen look like something wrong.
How solve this problem.?
