### ISSUE TITLE
Thank you so much for your valuable reply and also can you please help me how to edit formTransaction.vue file? And Tether USD icon is not showing.

### ISSUE THREAD

**Issue by tftwebteam** [hexters/CoinPayment#50]
Thank you so much for your valuable reply and also can you please help me how to edit formTransaction.vue file? And Tether USD icon is not showing.
Please your help means a lot.

_Originally posted by @tftwebteam in https://github.com/hexters/CoinPayment/issues/49#issuecomment-717809551_

**Comment by hexters** [comment]
Please update to V2.1.1 and see this [log update link](https://github.com/hexters/CoinPayment/releases/tag/v2.1.1)
