### ISSUE TITLE
Requesting to solve console data in coin payment checkout page

### ISSUE THREAD

**Issue by tftwebteam** [hexters/CoinPayment#51]
![Untitled](https://user-images.githubusercontent.com/66599002/97544244-55a9c680-19ef-11eb-8cce-981349b8f268.png)

Dear Hexters,
Please check the the attached file, in check out page hackers can easily able to change the value in console data. Please help me to resolve this issue.

**Comment by hexters** [comment]
I have a fixed this issue please update to the last version and republish the vendor force.

**Comment by tftwebteam** [comment]
Thank you so much, I am updating the package now and will check.

**Comment by tftwebteam** [comment]
Dear Hexter,
I have updated to new version of hexters coinpayment package, but still I am facing the same problem. The json data is visible in console and from there we can modify the data too.
Please find a solution to this.

**Comment by hexters** [comment]
`php artisan vendor:publish --tag=coinpaymen --force`

**Comment by tftwebteam** [comment]
Great. Thank you so much it worked.

**Comment by tftwebteam** [comment]
php artisan vendor:publish --tag=coinpayment --force
I run this in production server, but still json data is showing in console, but in local it worked fine. Is there any other way for production server?

**Comment by hexters** [comment]
Disabled / remove cache in your cloudflare.

Or hard refresh your browser.
