### ISSUE TITLE
Loading of mixxed content has been blocked. [HTTPS/SSL PROBLEM]

### ISSUE THREAD

**Issue by antonmk4** [hexters/CoinPayment#56]
The problem:

the transaction is not loading:
![problem](https://user-images.githubusercontent.com/69966869/106002561-93cb8a80-60b1-11eb-886d-c4d8ada2bb77.png)

I'm using clodflare as an proxy and i'm using "Automatic HTTPS Rewrites".

I tried everything but it just doesnt seem to work. Even tried Cloudflare Page Roules to force HTTPs

**Comment by hexters** [comment]
look at the page source and find the `_host` attribute in` <form-transaction _host="?"` what is the value?

**Comment by antonmk4** [comment]
You mean this? "show.blade.php"?
@section('content')
    <div id="app">
        <form-transaction _checkouturl="{{ request()->fullurl() }}" _host="{{ url('/') }}" _payload="{{ $payload }}"></form-transaction>
    </div>
@stop

**Comment by antonmk4** [comment]
> look at the page source and find the `_host` attribute in` <form-transaction _host="?"` what is the value?

Page source says: _host="https://MYDOMAIN.com"

**Comment by hexters** [comment]
Try to open `App\Providers\AppServiceProvider`

```php

. . .
namespace App\Providers;

use Illuminate\Support\Facades\URL; // add this

. . . 

public function boot()
{
      URL::forceScheme('https');

```

**Comment by antonmk4** [comment]
// 

> Try to open `App\Providers\AppServiceProvider`
> 
> ```
> . . .
> namespace App\Providers;
> 
> use Illuminate\Support\Facades\URL; // add this
> 
> . . . 
> 
> public function boot()
> {
>       URL::forceScheme('https');
> ```

// Working, thanks!
