### ISSUE TITLE
"Division by zero" error

### ISSUE THREAD

**Issue by pawelsome** [hexters/CoinPayment#8]
Hi,
i have this error when coinpayment card is open.
![przechwytywanie](https://user-images.githubusercontent.com/18335382/42892286-c25a185e-8ab1-11e8-93d1-4e1edcd4b35e.PNG)

I found that Rasputin Online Coin has rate_btc:0.000
![przechwytywanie2](https://user-images.githubusercontent.com/18335382/42892374-f88e5836-8ab1-11e8-81e3-5018b171f693.PNG)

This line is problematic in CoinPaymentController.php
$rate = ($rateAmount / $rates[$i]['rate_btc']);

**Comment by hexters** [comment]
$rateAmount cannot zero

**Comment by pawelsome** [comment]
I know, but i got it from coinmarket api yestarday. I think you should add additional securities.

**Comment by hexters** [comment]
Cek your account in www.coinpayments.net

**Comment by eadortsu** [comment]
i am still facing this issue. $rates[$i]['rate_btc']  is retruning 0

**Comment by pavelEspitia** [comment]
Same here

**Comment by nasirkhannstu** [comment]
Hey, Anyone find any solution of this problem??
